Made GstSpeechPlayer parent class of SpeechManager
connect_wave and connect_peak in speech.py takes in 2 arguments but 3 arguments are
passed when they're being used, before inheritance mouth movement didn't work.

The only change in this commit is making `SpeechManager` a subclass of GstSpeechPlayer
and that seemed to fix the mouth movement with a few hitches - idea gotten from espeak.py -.

Mouth movement now works but there's some issues,
typing 'hmmmm' or 'na' leaves the mouth ajar and that shouldn't happen
and logs still show this error
```
TypeError: connect_wave() takes exactly 2 arguments (3 given)
```
error existed before change and still exists after change but mouth movements work.